### ISSUE TITLE
Colored Icons

### ISSUE THREAD

**Issue by lamyergeier** [penguin-teal/gnome-openweather#33]
## Description

If I try to see weather with a quick glance I always fails due to all icons being very similar. All are grey.
It would be nice with a icon theme that looked more different. Blue rain, yellow sun, grey clouds, etc.

**Comment by penguin-teal** [comment]
Sorry, but the weather icons are provided by your system. So you can change your own icon theme to get different icons.
In terms of packaged icons the Adwaita ones are white, but I am going to keep them the way they are since those are the default GNOME icons. I tried changing them at one point to the Breeze icons to get more (since Adwaita only has a few) but I wasn't able to get any other icon set to render properly.
