### ISSUE TITLE
openweathermap custom API broken in v138

### ISSUE THREAD

**Issue by djandiek** [penguin-teal/gnome-openweather#57]
## Description

Version 138 breaks the custom API key even more than the last version. Previously I could save my key using `gsettings --schemadir ~/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/schemas set org.gnome.shell.extensions.openweatherrefined custom-keys "['', '<KEY>', '', '']"` but that no longer works with the latest version. 

## System

Ubuntu 24.04 LTS

## Settings

```json
{"app-version":"138","git-version":"138.r0.g6367a11","gnome-version":"46.0","user-locale":"en","custom-keys":["","<REDACTED>","",""],"appid":"<REDACTED>","actual-city":"1","weather-provider":"'openweathermap'","has-run":"true","locs":[{},{}],"show-sunsetrise-in-panel":"false","frozen":"false","weatherapidotcom-key":"<REDACTED>","geolocation-appid-mapquest":"<REDACTED>","disable-forecast":"true","position-in-panel":"'center'","show-comment-in-panel":"false"}
```

**Comment by TheRealWolfick** [comment]
This is not a bug.

First of all, the array should be three fields long, not four. Next, you are placing your key into the field for WeatherAPI, not OpenWeatherMap. The reason this worked before was because of a bug, which was just fixed.

Change your command to:

`gsettings --schemadir ~/.local/share/gnome-shell/extensions/openweather-extension@penguin-teal.github.io/schemas set org.gnome.shell.extensions.openweatherrefined custom-keys "['<KEY>', '', '']"`

**Comment by djandiek** [comment]
That worked, but I couldn't do it via the UI.

**Comment by TheRealWolfick** [comment]
> That worked, but I couldn't do it via the UI.

Neither can I. I don't know if this is a gnome-shell/wayland thing, the extension, or something else. Other people have been able to do it via the UI without issue so it is possibly not the extension causing this.

**Comment by penguin-teal** [comment]
The UI issue only affected certain API keys and has been fixed for the next release. Until then use the workaround described above.
