### ISSUE TITLE
Use more precise numbers for barometric pressure, remove some uncommon units

### ISSUE THREAD

**Issue by mulad** [penguin-teal/gnome-openweather#9]
This app has a lot of different options for showing current barometric pressure, but they all appear to be rounding to whole numbers. It's pretty typical for 3 to 5 (maybe 6) significant digits to be shown for atmospheric pressure units in other apps/sites, so there should be some better defaults, or the option to set the number of digits past the decimal point. This app is shortening many values to just 1 or 2 total digits, which isn't really enough to show changes.

I looked up standard atmospheric pressure, and the worldwide record low and high* values listed on Wikipedia, and determined how they would display as rounded numbers in the interface. (The high number is somewhat disputed, but it would round to the same value in many cases)

This is sorted with the order the different units show up in the app interface for me:

```
                             Records                 Rounded
Unit      Standard       Low        High       Low  Standard   High
----    -----------  ---------- -----------  ------ --------  ------
hPa       1013.25        870       1084.8       870     1013    1084
inHg        29.92         25.7       32.03       26       30      32
Pa      101325         87000     108480       87000   101325  108480
kPa        101.325        87.0      108.48       87      101     108
atm          1             0.858      1.0706      1        1       1
at           1.0332        0.887      1.1062      1        1       1
Torr       760           653        813.67      653      760     814
psi         14.6959       12.6       15.733      13       15      16
mmHg       760           653        813.67      653      760     814
mbar      1013.25        870       1084.8       870     1013    1084

```

And those are the most extreme measurements -- it's more typical to see a range between 950 mbar and 1050 mbar.

A user with pressure set to atmospheres (atm) or technical atmospheres (at) would never see the value change -- it will always be 1. Similarly, using ponds per square inch (psi) would probably only ever see values of 14 or 15, and people using inches of mercury (probably the most common way of displaying it in the United States) would generally only see values of 28 to 31.

I'd recommend removing the Pa, at, Torr, and psi units. Pa has too high of precision to really be useful, at and psi are used more for mechanical equipment rather than weather, and Torr is only slightly different than mmHg (they're so close together that they're only off by one part in seven million). I think it would also be good to remove hPa, since mbar is the same thing and appears to be the more common way to refer to it in weather contexts.

I'd recommend these as standard options, possibly with the ability to change the number of digits past the decimal point:

```
mbar    NNNN
kPa      NNN.N
inHg      NN.NN
mmHg     NNN.N
atm        N.NNN
```

**Comment by penguin-teal** [comment]
I think I'll keep some of the uncommon units because I don't see a point in removing functionality, especially because removing them would require migrating anyone's old preferences who may use these which I don't think is really worth it.
For the pressure precision I definitely agree— will add this.

**Comment by penguin-teal** [comment]
Added it (and ended up removing hPa), the default behavior is to now follow this custom pattern but you can otherwise set other precisions.
It looked like it was written for the pressure and wind speed precision to follow the temperature's which doesn't really work and isn't at all apparent in the settings menu (even I wasn't aware of this)! Now wind speed and pressure have separate options. I think the issue became more apparent when I changed the default decimal places for temperature to zero, before it was like 3 decimal places.
